# ===================================
#  Relation Behavior Config
# ===================================

videos:
    label: taema.youtubegallery::lang.plugin.controllers.videos.relation.label
    view:
        list: $/taema/youtubegallery/models/video/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/taema/youtubegallery/models/video/columns.yaml
        recordsPerPage: 10