# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: taema.youtubegallery::lang.plugin.controllers.playlists.name

# Model Form Field configuration
form: $/taema/youtubegallery/models/playlist/fields.yaml

# Model Class name
modelClass: Taema\Youtubegallery\Models\Playlist

# Default redirect location
defaultRedirect: taema/youtubegallery/playlists

# Create page
create:
    title: taema.youtubegallery::lang.plugin.controllers.playlists.create.title
    redirect: taema/youtubegallery/playlists/update/:id
    redirectClose: taema/youtubegallery/playlists

# Update page
update:
    title: taema.youtubegallery::lang.plugin.controllers.playlists.update.title
    redirect: taema/youtubegallery/playlists
    redirectClose: taema/youtubegallery/playlists

# Preview page
preview:
    title: Preview Playlist
