# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Video

# Model Form Field configuration
form: $/taema/youtubegallery/models/video/fields.yaml

# Model Class name
modelClass: Taema\Youtubegallery\Models\Video

# Default redirect location
defaultRedirect: taema/youtubegallery/videos

# Create page
create:
    title: Create Video
    redirect: taema/youtubegallery/videos/update/:id
    redirectClose: mathieutanguay/youtubegallery/videos

# Update page
update:
    title: Edit Video
    redirect: taema/youtubegallery/videos
    redirectClose: taema/youtubegallery/videos

# Preview page
preview:
    title: Preview Video
