# ===================================
#  Relation Behavior Config
# ===================================

playlists:
    label: taema.youtubegallery::lang.plugin.controllers.playlists.relation.label
    view:
        list: $/taema/youtubegallery/models/playlist/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/taema/youtubegallery/models/playlist/columns.yaml
        recordsPerPage: 10